### ISSUE TITLE
how to extract world coordinate of one object (ifcdoor) from ifc file

### ISSUE THREAD

**Issue by hyq1991** [xBimTeam/XbimGeometry#100]
Hi, I try to use xbim get extract coordination information of door. Is there any way that I can get this information??

**Comment by martin1cerny** [comment]
Yes, there is [IfcDoor.ObjectPlacement](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcobjectplacement.htm).

**Comment by hyq1991** [comment]
I think this give me relative coordinate. If I want to find the location in CS. Is there anyway I can quickly do that?

**Comment by LoganQiong** [comment]
@hyq1991 Hope to help you。
    static string _ifcFile = @"E:\SampleHouse.ifc";
    private static void Main(string[] args)
    {
        using (var model = IfcStore.Open(_ifcFile))
        {
            var context = new Xbim3DModelContext(model);
            context.CreateContext();

            var geometrys = context.ShapeGeometries();
            var instances = context.ShapeInstances();

            string jsonString = "";
            foreach (var instance in instances)
            {
                string faces_json = "";
                string point_json = "";

                var transfor = instance.Transformation;
                var matrixItem = transfor.ToString().Split(' ');
                var matrix4 = JsonConvert.SerializeObject(matrixItem);

                var geometry = context.ShapeGeometry(instance);
                var data = ((IXbimShapeGeometryData)geometry).ShapeData;

                using (var stream = new MemoryStream(data))
                {
                    using (var reader = new BinaryReader(stream))
                    {
                        var mesh = reader.ReadShapeTriangulation();

                        List<XbimFaceTriangulation> Faces = mesh.Faces as List<XbimFaceTriangulation>;
                        faces_json = JsonConvert.SerializeObject(Faces);

                        List<XbimPoint3D> Point = mesh.Vertices as List<XbimPoint3D>;
                        point_json = JsonConvert.SerializeObject(Point);
                    }
                }
            }
        }
     }

**Comment by Belrius** [comment]
Just in case anyone else has the same question, as I did, here's a more direct answer to the OP's question.

`            using (var model = IfcStore.Open(fileName, editor, false))
            {
                //       using (var txn = model.BeginTransaction("Quick start transaction"))
                {
                    var context = new Xbim3DModelContext(model);
                    context.CreateContext();
                    var instances = context.ShapeInstances();

                        // do stuff. get the door that you need

                    var instance = instances.FirstOrDefault(x => x.IfcProductLabel == door.EntityLabel);
                    var global_pos = instance.Transformation.Translation;

`

**Comment by andyward** [comment]
Thanks @Belrius

**Comment by c-falardeau** [comment]
Is that possible without using geometries but information stored using the IFC store directly?

Me I would like to get the world coordinates of each IFCPRODUCT in the FILE?
After that I would like to change their position to get near 3D origin

Is that possible just using the IFC store?

**Comment by mwymwy** [comment]
> Hi, Is that possible without using geometries but information stored using the IFC store directly?
> 
> Me I would like to get the world coordinates of each IFCPRODUCT in the FILE? After that I would like to change their position to get near 3D origin
> 
> Is that possible just using the IFC store?


Yep, of course you can.

It does involve few mathematics though.
you can parse store's instances with .OfType<IIfcProduct>()

Each IfcProduct has an ObjectPlacement, 
Usually, this placement is of RelativePlacement kind which can be considered as a transformation to go from the parent Placement coordinate system to the Object coordinate system.

The parent Placement can be relative too, and so on.
So in order to go from an Object coordinates system to a global coordinate system, you have to multiply every coordinate system matrix until no more Related Placement is found, or Related Placement is null.

...
BUT !

Sometimes this can give out unsatisfying reason, for example when a product has a relative placement at one place, but its representations themselves are not really in the same place. I saw few examples of Ifc files where this situation occurs.

Using the geometry engine helps a lot with everything that is geometry related. In fact it does an incredible job at turning homogeneous geometry information, masking all the complexity of the geometry and representation Ifc classes.

To my opinion, it really does matter that you ask yourself if the position you want is the IFC product declared position as it exists in the file, or if you want an accurate 3D position of the visual representation of the product.


Second part of your job : changing position to get near 3D origin :
the easier way I can figure is to create one ObjectPlacement, placed wherever you want to, and to replace each and every other ObjectPlacement of the products by this new one.

**Comment by c-falardeau** [comment]
Hello mwymwy,

thank you for your answer. I think it will help. For me IFC is really complex to learn and have sometimes hard to firgure out relation ship.

Do you have a snipper of code or a url to share that shows how to convert local placement in 3D converting the IFC to matrix transformation?

We need to federate models together but can't use XBim toolkit since our files are preprocessed independently. And adjustWCS cannot be used since it would remove rotation of the model.

And yes we currently move the model by applying translation to product once the geometries are generated but I don't why it does not work on some models. 

Also when the first IFCLOCALPLACEMENT in the file is (0, 0, 0) creating the geometries make them look fuzzy because of float precision lost.

Thank you for hepl and hint

Best  regards,
Christian

**Comment by mwymwy** [comment]
> Hello mwymwy,
> ...
> 

Yeah you right Ifc is not exactly easy to master.
It definitely has some complexities here and there that would make one ask "But ... why ?"

But on the other hand, it really is interesting to navigate through its STEP structure and understand all the endless possibilities of managing building data at any scale that would fit your needs.

I do have some code that I may share with you, it was implemented as an extension function to the IIfcProduct interface :

`
public static XbimMatrix3D GetTransformation(this IIfcProduct product)
        {
            List<XbimMatrix3D> matrixList = new List<XbimMatrix3D>();
            XbimMatrix3D result = new XbimMatrix3D();
            IIfcLocalPlacement lp = product.ObjectPlacement as IIfcLocalPlacement;

            if (lp == null) { return XbimMatrix3D.Identity; }

            IIfcLocalPlacement relPlace = lp.PlacementRelTo as IIfcLocalPlacement;
            XbimMatrix3D objTr = lp.RelativePlacement.ToMatrix3D();
            matrixList.Add(objTr);

            while (relPlace != null)
            {
                XbimMatrix3D tr = relPlace.RelativePlacement.ToMatrix3D();
                matrixList.Add(tr);
                relPlace = relPlace.PlacementRelTo as IIfcLocalPlacement;
            }

            foreach (XbimMatrix3D m in matrixList) { result = XbimMatrix3D.Multiply(result, m); }

            return result;
        }
`

It is maybe not the prettiest code I wrote, but it does the job at returning an XbimMatrix3D representing the whole product placement in a global coordinates system.

From there you should be able to do whatever you want.

For your fuzzy geometries problems, I had this kind of issues few times.

Consider that using models with large coordinates is usually the worst way to store an information about the model being placed quite far away from a given reference point.

This information should better be stored as latitude/longitude/elevation coordinates, for example.
Or in a custom attribute, wherever you want, storing lambert-coordinates or any geo-coordinates.

Inside the model itself, every Cartesian point and every translation, and every 3D related information, should have coordinates 
with dimensions related to the size of the model itself.

Search your ifc file with a notepad++ or any other text editor that allow regular expression research.
You should be able to identify what lines (and what objects) contains large coordinates.
While I saw, one day, a file with coordinates that go beyond 800-900 kms, I can't figure a proper reason why it would be the right thing to do.

**Comment by c-falardeau** [comment]
Hello mwymwy, 

Nice thanks, I will check in more depth your answer this week, but thanks again for the help 

it is really appreciated

**Comment by martin1cerny** [comment]
Hello @mwymwy, thanks for supporting the community.

**Comment by SSeelos** [comment]
@mwymwy 
> I do have some code that I may share with you, it was implemented as an extension function to the IIfcProduct interface
...

Thanks for your contribution!
as i was implementing your solution i tried to make it more modular and concise.
This might be helpful for some:
```
public static XbimMatrix3D GetTransform(this IIfcProduct product)
    => product.ObjectPlacement.GetTransform();

public static XbimMatrix3D GetTransform(this IIfcObjectPlacement placement)
{
    if (!(placement is IIfcLocalPlacement local))
        return XbimMatrix3D.Identity;

    return local.GetTransform()
        * local.QuRelToPlacements().GetTransform();
}

public static XbimMatrix3D GetTransform(this IIfcLocalPlacement placement)
    => placement.RelativePlacement.ToMatrix3D();

public static XbimMatrix3D GetTransform(this IEnumerable<IIfcLocalPlacement> placements)
{
    return placements.Select(p => p.RelativePlacement)
        .GetTransform();
}

public static IEnumerable<IIfcLocalPlacement> QuRelToPlacements(this IIfcLocalPlacement placement)
{
    IIfcObjectPlacement other = placement.PlacementRelTo;
    while (other is IIfcLocalPlacement localPlacement)
    {
        other = localPlacement.PlacementRelTo;
        yield return localPlacement;
    }
}
```
