### ISSUE TITLE
Xbim.ModelGeometry wrong

### ISSUE THREAD

**Issue by hyq1991** [xBimTeam/XbimGeometry#101]
I try to run the codeexample of xbim, which I downloaded from https://github.com/bnaand/xBim-Toolkit using visual studio 2017. however, it get wrong Exception thrown: 'System.Exception' in Xbim.ModelGeometry.Converter.dll. Could not load the Geometry engine at C:\Users\coaadmin\Desktop\xBim-Toolkit-master\xBim-Toolkit-master\CodeExamples\bin\Debug\x64\Xbim.ModelGeometry.OCCd.dll. Is there anyway I can fix this problem?

**Comment by martin1cerny** [comment]
You will need to ask @bnaand or @xyicheng because all this code is very old and seems to be forked from xBIM at least 4 years ago. Neither @bnaand or @xyicheng are members of @xBIMTeam.
Read our documentation at http://docs.xbim.net/ to get started with latest xBIM. Preferred way to use xBIM is via NuGet packages. To get the very latest versions you can use our MyGet feed as described on the website above.

**Comment by bnaand** [comment]
@hyq1991, exactly as @martin1cerny said. That fork is old and not maintained. Please use official version.
