### ISSUE TITLE
Question regarding geometry 

### ISSUE THREAD

**Issue by twoelfer** [xBimTeam/XbimGeometry#107]
hi.

I can read all the XbimShapeInstances für the IIfcProducts that i want and i can also get the XbimShapeTriangulation usgin ReadShapeTringulation().

Basically, this gives me all the meshes i need for use in visualization. However, i do actually need something else. Given that the meshes appear to be calculated by xbim, i assume there is also information regarding the edges of the products. (That's what i'm actually looking for.)

Is there an easy (any ?) way to get these edges?

**Comment by lucasaue** [comment]
Well, easy way I don't know, but you can calculate this edges.

When you say edges, I think in that you wanna the Outline, that's all external edges from mesh.

If is just for visualization, like a selection, or Wireframe visualization, I recomend you to use a shader, because the calculation is more simple and fast. In unity you have this example:

[https://answers.unity.com/questions/1226994/outline-rendering.html](https://answers.unity.com/questions/1226994/outline-rendering.html)

But, if you need the polys with points, you can use this algorithm:

Boundary edges are only referenced by a single triangle in the mesh, so to find them you need to scan through all triangles in the mesh and take the edges with a single reference count. You can do this efficiently (in O(N)) by making use of a hash table.

To convert the edge set to an ordered polygon loop you can use a traversal method:

 - Pick any unvisited edge segment [v_start,v_next] and add these vertices to the polygon loop.
 - Find the unvisited edge segment [v_i,v_j] that has either v_i = v_next or v_j = v_next and add the other vertex (the one not equal to v_next) to the polygon loop. Reset v_next as this newly added vertex, mark the edge as visited and continue from 2.
 - Traversal is done when we get back to v_start.

The traversal will give a polygon loop that could have either clock-wise or counter-clock-wise ordering. A consistent ordering can be established by considering the signed area of the polygon. If the traversal results in the wrong orientation you simply need to reverse the order of the polygon loop vertices.

If you wanna more information, I recomend you take a look in this post:

[https://stackoverflow.com/questions/14108553/get-border-edges-of-mesh-in-winding-order](https://stackoverflow.com/questions/14108553/get-border-edges-of-mesh-in-winding-order)

**Comment by twoelfer** [comment]
Thank you, this helps, and i can use this to get to the polygon points I need. However, given that "something" is creating those meshes based on some data in the file, i would have thought there was a method to get to the "original" data that was used to create the meshes in the first place - instead of un-triangulating the meshes. :-)

Anyhow, works.

**Comment by martin1cerny** [comment]
Can I close this issue now?

**Comment by twoelfer** [comment]
Yes please. (Should i have done something ? I don’t really know how github works…)
 
Von: Martin Černý <notifications@github.com> 
Gesendet: Donnerstag, 24. Mai 2018 10:54
An: xBimTeam/XbimGeometry <XbimGeometry@noreply.github.com>
Cc: twoelfer <tw@die.de>; Author <author@noreply.github.com>
Betreff: Re: [xBimTeam/XbimGeometry] Question regarding geometry (#107)
 
Can I close this issue now?

**Comment by martin1cerny** [comment]
You could press **Close** button bellow the conversation thread :-)

**Comment by twoelfer** [comment]
Ok, thank you, i’ll remember to do this next time…
 
Von: Martin Černý <notifications@github.com> 
Gesendet: Donnerstag, 24. Mai 2018 12:19
An: xBimTeam/XbimGeometry <XbimGeometry@noreply.github.com>
Cc: twoelfer <tw@die.de>; Author <author@noreply.github.com>
Betreff: Re: [xBimTeam/XbimGeometry] Question regarding geometry (#107)
 
You could press Close button bellow the conversation thread :-)
