### ISSUE TITLE
XbimGeometry.Engine on an Azure Web App

### ISSUE THREAD

**Issue by Vizzr** [xBimTeam/XbimGeometry#112]
I'm trying to show an IFC model in the webpage. 
This works when using a local instance such as localhost or ip.

However, when the application is deployed as an Azure Web App, the XbimGeometry.Engine32 and 64 dlls cannot be found.

Both the architecture engine files are located under bin/x**yy**/XbimGeometry.Engine**yy**.dll

#### Expected behavior:
I expect it to show an IFC-model in the web page.

Localhost:
![image](https://user-images.githubusercontent.com/36069685/40981703-e63bc0d0-68db-11e8-838c-c777df2a14ff.png)

#### Actual behavior or exception details:
It doesn't show anything.
The error happens when generating the .wexBIM file.

`"ExceptionMessage":"Could not load file or assembly 'Xbim.Geometry.Engine32' or one of its dependencies. The system cannot find the file specified.","ExceptionType":"System.IO.FileNotFoundException","StackTrace":"   at Xbim.Geometry.Engine.Interop.XbimGeometryEngine..ctor() in c:\\BuildAgent\\work\\860c3b913b6c647f\\Xbim.Geometry.Engine.Interop\\XbimGeometryEngine.cs:line 42\r\n   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.get_Engine() in c:\\BuildAgent\\work\\860c3b913b6c647f\\Xbim.ModelGeometry.Scene\\Xbim3DModelContext.cs:line 528\r\n   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext(ReportProgressDelegate progDelegate, Boolean adjustWcs) in c:\\BuildAgent\\work\\860c3b913b6c647f\\Xbim.ModelGeometry.Scene\\Xbim3DModelContext.cs:line 658\r\n`

#### Versions of xBIM Packages:

- xBIM Geometry: 4.0.11

How can I resolve this issue?

**Comment by LloydPickering** [comment]
At a guess that would be because Azure Web App probably supports .net, but not the unmanaged c++ code required by the geometry engine to do the initial conversion of geometry.

In my mind you have two-three choices (perhaps others too, or variations on a theme)

1) Is it the same file for every page visit? If so, pre-generate the .xbim file (or a wexbim file) offline, and load that instead of the ifc. The geometry engine doesn't need to load as it already has the geometry in place. Benefit of this is it will be faster too as it doesn't have to parse the ifc or generate the geometry.
2) If its potentially a different ifc file every page visit, you have 2 options:
a) Move from a hosted Web App to a Windows VM running IIS, which would support the C++ code
b) Upload ifc files to some sort of backend process which is capable of generating xbim or webxbim files, which can be subsequently used by your Web App

**Comment by Vizzr** [comment]
Thanks for the reply.

The wexbim file is not a static one. It is used for different models.

Maybe you are right about the Azure Web App not supporting unmanaged c++ code, but wouldn't it give a different error then?

"System.IO.FileNotFoundException" doesn't sound like an error that means "I cannot load unmanaged code".

Anyways, I will keep searching and keep this topic up to date.
Or else I might move to your second point.

**Comment by Vizzr** [comment]
**FIXED IT!!!!!!!!**

Okay I maybe know the cause of the problem.
I think that the IIS manager fixed the reference to the x86 and x64 engine dlls.

As said earlier, the engine dlls are in their specific folder:
bin/x**yy**/XbimGeometry.Engine**yy**.dll

However, when looking at the Azure Web App files, the engine files are not deployed.

**No reference is made to the engine files in the C# Visual Studio project.**
Only to the interop.

The files are here in the project:
![image](https://user-images.githubusercontent.com/36069685/41025642-bd25ae12-6972-11e8-9700-2f6ab8692baa.png)

and their properties:
![image](https://user-images.githubusercontent.com/36069685/41025669-cf6c16c4-6972-11e8-955c-f68c3f209bbd.png)

It says: Do not copy to output (**eventhough the bin is already the output**).
When I do want to say "Copy to output directory" I get this error:

![image](https://user-images.githubusercontent.com/36069685/41025865-5744ec9c-6973-11e8-88f9-08a3a21fa1ed.png)

**When I manually add a reference to the engine files, the files do get deployed.**

I then received an error because the Web App was a 32bit version.

**So i added the 32bit version of Xbim.Geometry.Engine32.dll as a reference and deployed the application.
It is now deployed and fully working.**

Only downside to this is that it only works on the 32bit.
Is there a way to reference both 32 and 64 bit without crashing the application?

**Comment by CBenghi** [comment]
@Vizzr 

I think all is good...

If you see the engine working it's safe to assume that you are using the correct version of the dll.
This is because the C++ libs are loaded through reflection in our code, and the file name is determined from the memory architecture which is currently running. The x86 files would be ignored on a x64 machine.

Best,
Claudio

**Comment by andyward** [comment]
There's been a change in this are in v5 that should help
