### ISSUE TITLE
[Question] How to create multi-material element

### ISSUE THREAD

**Issue by sanderobdeijn** [xBimTeam/XbimGeometry#115]
How can you create a multi material element in 2x3?
I have an IfcSlab that is created by and an extrusion or a booleanresult that should have 2 materials.
I have created and IfcMaterialLayerSet and created an IfcRelAssociatesMaterial to connect it to the IfcSlab but this doesn't change the representation in an IfcViewer. Should I set it somewhere else also?

**Comment by martin1cerny** [comment]
Material and colour representation are two different concepts in IFC. See [IfcSyledItem](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcstyleditem.htm) for details.

**Comment by martin1cerny** [comment]
Reading through the question again, also note that most of the IFC viewers don't show material layers defined in `IfcMaterialLayerSet` because it requires relatively a lot of work with graphics to lay down some sensible 2D cutting representation of these layers on top of 3D geometry. It is often easier to present the material layer structure in a separate view of some kind.
