### ISSUE TITLE
BooleanTimeOut not working as expected

### ISSUE THREAD

**Issue by danmac03** [xBimTeam/XbimGeometry#119]
#### Actual behavior or exception details:
Trying to import an IFC and for some reasons in some files the BooleanTimeout is not working as expected. It timesout after more time than expected. Even if I add the configuration variable to my app config file seems like I still get the same behavior. I would expect the Timeout to occur based on the time set inside the config file or even the default value which is less than what I see in the console app. 

*Screenshot or image of desired state:*
This is a screenshot of what I get inside my console app when I import the IFC.
![booleantimeout](https://user-images.githubusercontent.com/37149135/42378868-d3ef0cec-80f6-11e8-84f8-6ef1752dfbfd.png)

#### Versions of xBIM Packages:

- xBIM Essentials: 4.0.30-V022
- xBIM Geometry: 4.0.15-V0039

Any idea what could lead the timeout not working as designed?

**Comment by SteveLockley** [comment]
Time Out is based on a call back from the boolean engine in open cascade, we do no control when OCC makes this call back, it will depend on the complexity of the model it is processing. We look at the time elapsed since the operation started and if exceeds the time out we kill the operation. Hence it is possible that actual time out is longer than the specified. The issue is really the complexity of the boolean operation, if you can post an example file that generates this value I will investigate whether the problem is really the geometry operation.

**Comment by SteveLockley** [comment]
In release 5 this is now resolved. We no longer use the Opencascade time out and instead use native thread time outs. Any boolean in a thread will time out at the specified value
