### ISSUE TITLE
Issues with XBIM 32bit dll

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimGeometry#14]
I have developed a BIM application that integrates with another application (let’s say application B). Now application B uses a 32bit dll. In order for this application to work I need to enable 32 bit applications to true in IIS application pool. But here lies the problem. XBIM source consists of two dll’s (32-bit and 64-bit). The dll is responsible for converting IFC file – XBIM – WEXBIM. Now both these processes need to happen together in my application.

For application B to run , it’s mandatory that the condition remains true in IIS. However whenever this condition is true the XBIM uses the 32bit dll automatically which fails to convert ifc files over the size of 900 mb.(to be specific the XBIM conversion stops at 880 mb). I need to convert a 1gb(or even more) ifc file. The error that is shown is (stack overflow at the 32bit XBIM dll). However when I set the condition (enable 32bit application) to false in IIS, XBIM uses the 64 bit dll and successfully converts IFC – XBIM – WEXBIM.

Now I need the condition to be set to true all the time for my App B to work. Is there any way that this 32 bit XBIM Conversion dll can be bypassed and we can force it to use the 64 bit dll all the time even if the condition in IIS is true??
Need urgent help on this!!

**Comment by LloydPickering** [comment]
The 32/64 bit dll is chosen based on the platform's runtime pointer size (32 or 64bit sized intptr). You could conceivably change this if you wanted to force 64bit, but ultimately if IIS is a 32 bit process, you won't be able to run a 64bit conversion process.

The only way you are going to be able to solve this while keeping the front end 32bit is to put your IFC conversion process somewhere other than the IIS thread. I would strongly recommend doing this in any case as otherwise you are blocking your front end web services with CPU and memory intensive conversion of IFCs.

Why not consider using something like http://hangfire.io/ to process the IFC file on a backend service (the downside is it is fire and forget, unless you use some form of inter-server communications which are well beyond the scope of this project).

**Comment by SteveLockley** [comment]
This is a deployment issue and not really in the scope of the project, look in the Assembly loader code of Xbim.Geometry.Interop to see how to control dll loading.
