### ISSUE TITLE
Solid conversion with IfcTriangulatedFaceSet fails

### ISSUE THREAD

**Issue by guenter1holzeder** [xBimTeam/XbimGeometry#148]
Attached IFC contains a SOLID IfcColumn rendered with IfcTriangulatedFaceSet. Using the GeometryEngine to get a solid will fail.

 
![image](https://user-images.githubusercontent.com/42930849/49810276-2e956d80-fd61-11e8-932a-512e17d9c55f.png)

    var store = IfcStore.Open(@"C:\Development\Daten\IFC\_IFC Measures\column-straight-rectangle-tessellation.ifc", null, 0);

    var element = store.Instances.OfType<IIfcElement>().FirstOrDefault(e => e.EntityLabel == 71);

    foreach (var representation in element.Representation.Representations)
    {
        foreach (var item in representation.Items)
        {
            IXbimGeometryEngine geometryEngine = new XbimGeometryEngine();

            if (item is IIfcTriangulatedFaceSet triangulatedFaceSet)
            {
                var solidSet = geometryEngine.CreateSolidSet(triangulatedFaceSet);
                Console.WriteLine(solidSet.Count);

                var set = geometryEngine.CreateSurfaceModel(triangulatedFaceSet);
                var shell = set.Shells.First;

                Console.WriteLine(shell.IsClosed);
                Console.WriteLine(shell.CanCreateSolid());
            }
        }
    }

[column-straight-rectangle-tessellation.zip](https://github.com/xBimTeam/XbimGeometry/files/2668157/column-straight-rectangle-tessellation.zip)

**Comment by guenter1holzeder** [comment]
Ok, IXbimGeometryObjectSet.Sew() does the right job. But in some cases the method "kills" the ShellSet if no Solids could be formed.

What is the optimal way for using Sew()?

**Comment by SteveLockley** [comment]
Guenter we have just done a lot of work on shells and faceted Breps to help with these issues.
If a Faceted Brep is a closed shell and it is proposed through the geometry engine rather than the Tessellation engine, then the Sew will be done during processing. Sew fails or goes unbelievably slowly when there are more than say 1000 faces, there is an environment variable that controls this maximum  number of faces to try and sew SimplifyFaceCountThreshHold. We also changed the behavior so that it does not kill the shell if it fails to make the solid. (Basically in the latest version in develop you should not need to worry about Sew)

**Comment by guenter1holzeder** [comment]
Thanks for your improvments
