### ISSUE TITLE
XbimShapeTriangulation into quads?

### ISSUE THREAD

**Issue by Freiza** [xBimTeam/XbimGeometry#164]
XbimShapeTriangulation gives me indices as triangles, I want quad is there any way to get quads instead of triangle?

**Comment by martin1cerny** [comment]
I'm sorry, but what do you mean by 'quad'?

**Comment by bekraft** [comment]
Hey, maybe you'll mean quadrilateral faces (having 4 vertices instead of 3). Xbim tesselation only knows about triangles (and even the IFC does not support it unless you restrict yourself to planar faces). So a quad would mean to me to have a (possibly non-planar) face with 4 vertices and 4 vertex normals. Right? The Xbim tesselator should have everything in place except for combining two adjacent triangles into a quad. This would be path to follow, isn't it?
