### ISSUE TITLE
IFCCARTESIANPOINTLIST3D generated contains additional redundant field?

### ISSUE THREAD

**Issue by WindingWinter** [xBimTeam/XbimGeometry#175]
1. Run this code [Point3DIFCrepresentation.zip](https://github.com/xBimTeam/XbimGeometry/files/3150414/Point3DIFCrepresentation.zip).
2. Focus on the generated output ifc file, the line involving `IFCCARTESIANPOINTLIST3D` (eg: `#32=IFCCARTESIANPOINTLIST3D(((0.,0.,0.),(0.,100.,0.),(100.,100.,0.),(0.,100.,100.)),$);`)
3. I wonder why there is a `$`? Because according to the[ IFC specification](http://www.buildingsmart-tech.org/mvd/IFC4x1/Alignment/1.0/html/schema/ifcgeometricmodelresource/lexical/ifccartesianpointlist3d.htm), there isn't any "optional" field after the coordinates.
4. Note that the presence of this optional field causes [Civil3D unable to parse the IFC file correctly](http://www.buildingsmart-tech.org/mvd/IFC4x1/Alignment/1.0/html/schema/ifcgeometricmodelresource/lexical/ifccartesianpointlist3d.htm). 

I'm using xBIM 4.0 by the way, not sure whether it matters or not...

**Comment by martin1cerny** [comment]
The documentation you are pointing to **is not the official final schema for IFC4x1.** The [final schema](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/link/ifccartesianpointlist3d.htm) contains `Tag` attribute. Also, STEP21 specification says that if there is a property found at the end which is not recognized it should be ignored. It is a standard method to extend the schema in a backwards compatible & non-destructive way.

So, Civil3D is implementing an old version of IFC4x1 schema (one of [Release Candidates](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/link/annex-f.htm)) and is not supporting Step21 extensibility. You can see the versions changelog [here](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/link/annex-f.htm). I've seen some sample files produced before which were implementing RC1which is **3 years** behind the final release. IFC5 extensions should be build on top of the **final release** and that is what we implement.

You should report this back to Civil3D if you can because it is making very bad service to IFC by supporting the **initial draft** instead of the **final standard**.

**Comment by WindingWinter** [comment]
> The documentation you are pointing to **is not the official final schema for IFC4x1.** The [final schema](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/link/ifccartesianpointlist3d.htm) contains `Tag` attribute. Also, STEP21 specification says that if there is a property found at the end which is not recognized it should be ignored. It is a standard method to extend the schema in a backwards compatible & non-destructive way.
> 
> So, Civil3D is implementing an old version of IFC4x1 schema (one of [Release Candidates](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/link/annex-f.htm)) and is not supporting Step21 extensibility. You can see the versions changelog [here](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/link/annex-f.htm). I've seen some sample files produced before which were implementing RC1which is **3 years** behind the final release. IFC5 extensions should be build on top of the **final release** and that is what we implement.
> 
> You should report this back to Civil3D if you can because it is making very bad service to IFC by supporting the **initial draft** instead of the **final standard**.

Thank you so much for your clarification

**Comment by martin1cerny** [comment]
You are welcome. If you have any updates on Civil3D support for IFC, I'd be very happy to hear more about that.

**Comment by WindingWinter** [comment]
I'm asking them to fix this, let's see how it goes.
