### ISSUE TITLE
Revit IFCs: Very slow processing and Out of memory exceptions

### ISSUE THREAD

**Issue by andyward** [xBimTeam/XbimGeometry#176]
Revit exporter 17.3.0.0 is outputting some  IFC Geometry in a manner that's causing model processing to take hours & consume a lot of memory (resulting in crashes)

#### Assemblies and versions affected:

V5 Geometry v5.0.118

#### Minimal file to reproduce the issue:

See `mp101-sw02-03-zz-a-mdi-xxxx-0100-0002.ifc` provided privately by BT.

... which took 4 hours before crashing. 

![image](https://user-images.githubusercontent.com/923699/57390328-fed57f00-71b3-11e9-90bd-85c17c427e1c.png)

**Comment by SteveLockley** [comment]
This was caused by a huge polygonal mesh (representing louvres for a wall) with an opening cut into them. This is beyond the reasonable limits of Opencascade boolean operations and takes a considerable and unreasonable length of time. The operations are not really sensible, it has been trapped and a warning issued, the mesh geometry has been preserved to give some indication of location but the boolean has been aborted to allow the rest of the model to complete

**Comment by andyward** [comment]
Confirmed fixed in _Geometry 5.0.216-develop_. 

Took 16 mins, and memory usage was reasonable.

![image](https://user-images.githubusercontent.com/923699/57685129-1fc42700-762f-11e9-9749-05bb4e43e554.png)
