### ISSUE TITLE
Floor Type not zooming in xBIM Viewer

### ISSUE THREAD

**Issue by Nandhakumar2187** [xBimTeam/XbimGeometry#264]
Hi,

We have uploaded the IFC file and converted in to JSON & wexbim format and displayed in xBIM Viewer.

If we double click on the entity type "floor" (this floor **does not contain** any spaces, asset, etc) from tree menu  - the selected entity type not zooming in xBIM Viewer.

If we double click on the entity type "floor" (this floor **containing** spaces, asset, etc) from tree menu  - the selected entity type will be zoomed and displayed in xBIM Viewer.

Please provide the solution to highlight the entity type (especially "Floor" type) in xbIM viewer if that not contains any spaces, assets, etc.

Thank you in advance.

**Comment by andyward** [comment]
This is a WebUI limitation rather than geometry.

Regardless of the UI implementation, zooming to an element in 3D requires there to be geometry representation to calculate a bounding box. 

Floors (i.e. IfcBulildingStorey's) usually won't have representation defined from the design tool - they are typically just a spatial concept, aggregating a set of IfcSpaces which generally do have representation. If a Floor doesn't have spaces associated there's no easy means determine its extents. 

You could probably do something to locate the top & bottom of the level from the IfcBuildingStorey Elevation etc and manually set the camera/lookAt on some assumed center point of the level - but that's outside the responsibility of the the web viewer -which doesn't have access to that data.

**Comment by CBenghi** [comment]
Alternatively, a storey might contain spaces, and you can decide to zoom to
the spaces that constitute the storey.
