### ISSUE TITLE
Problem with IFCCARTESIANPOINT in a Polyline used in IFCARBITRARYCLOSEDPROFILEDEF

### ISSUE THREAD

**Issue by PIUM-arc** [xBimTeam/XbimGeometry#277]
Hello,

I'm facing an issue I that I don't understand :

I have a 2x3 IFC containing IFCARBITRARYCLOSEDPROFILEDEF objects. When I open this file on the XBimExplorer exe available on your website I don't have any issue but when I try to open it using the XBim library (XbimWindowsUI) sources, I have a warning on any IFCARBITRARYCLOSEDPROFILEDEF and the viewer fail creating the geometry ( the geometry is considered as empty).

Here is the warning :  _[WRN] GeomEngine: #350045023=IfcArbitraryClosedProfileDef [The curve used for the outer curve definition shall have the dimensionality of 2. Error in IFC file_

Here is an example of the IFC file : 

```
#30020023=IFCARBITRARYCLOSEDPROFILEDEF(.AREA.,'Z3000',#30020200);

/* 200 Polyline - Vertex*/
#30020201=IFCCARTESIANPOINT((35211.35,59679.69,0.00));
#30020202=IFCCARTESIANPOINT((32150.51,59679.69,0.00));
#30020203=IFCCARTESIANPOINT((32150.51,56879.69,0.00));
#30020204=IFCCARTESIANPOINT((32661.35,56879.69,0.00));
#30020205=IFCCARTESIANPOINT((32661.35,56218.86,0.00));
#30020206=IFCCARTESIANPOINT((32150.51,56218.86,0.00));
#30020207=IFCCARTESIANPOINT((32150.51,56168.86,0.00));
#30020208=IFCCARTESIANPOINT((35211.35,56168.86,0.00));
#30020209=IFCCARTESIANPOINT((35211.35,59679.69,0.00));
#30020200=IFCPOLYLINE((
	#30020201,#30020202,#30020203,#30020204,#30020205,
	#30020206,#30020207,#30020208,#30020209));
```

So, if I change the dimension of the IFCCARTESIANPOINT from 3 to 2 I don't have the problem anymore.

I would like to understand why the viewer exe with older assemblies can open the IFC file without any problems but not the library, and why the cartesian point in 3 dimension are considered as an error.

Thank you

**Comment by bekraft** [comment]
The error happens due to the IFC2x3 specification. It defines a "Where Rule" which declares a constrains the use to 2D curves only. See [IFCARBITRARYCLOSEDPROFILEDEF](https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcprofileresource/lexical/ifcarbitraryclosedprofiledef.htm#definition). From geometrical perspective it's really difficult to determine whether a figures is planar or not. So the existence of this rule ensures, that only planar base profiles are given. Basically, it's an schema issue with your exporting software.
Older versions may have skipped this rule.

**Comment by PIUM-arc** [comment]
Thank you for the precision, but I'm not sure to totally understand. This rule that constrains the use of 2D curves only is not new, but the different IFC viewer I tried succeeded in solving the geometry of my IFC file using 3D curves, does this mean that those viewers are not up to date and don't respect this rule ? If they can still solve the geometry, is this rule really mandatory ?

**Comment by bekraft** [comment]
Those rules are meant to avoid problems of meaning which are not captured by the schema itself. Means: You can specify 3D coordinates and according to the schema it's ok, but no one (and also not the viewer in use) can ensure that the geometry is displayed correctly, if you break the constraints. Since the schema doesn't express 2D and 3D in separate entities, it's mandatory. But you can deal with this in different ways.

Most viewers don't check these rules, since they are given in functional STEP syntax. Your viewer will likely ignore the third coordinate value since it knows about the rule (and doesn't complain). So it client-optimistic and failure safe ... Xbim complains about this - and doesn't show results. I personally like the way to complain but to serve the client's wishes ;-)

**Comment by PIUM-arc** [comment]
Ok, thank you for the precision !

**Comment by bekraft** [comment]
Before really closing this: Is there any example to share? Maybe it's worth to check whether Xbim logs a warning / or a warning is triggered during validation.
