### ISSUE TITLE
Why many Tests start with MemoryModel and Transaction?

### ISSUE THREAD

**Issue by Hafplo** [xBimTeam/XbimGeometry#362]
Looking at the code for Tests, many of them start with opening a new MemoryModel followed by beginning a Transaction.
Is it necessary?
Can we test the same functionalities by using small IFC files instead? (I.e. the files from TestFiles folder)

#### Assemblies and versions affected:

[Xbim.Geometry.Engine.Interop.Tests](https://github.com/xBimTeam/XbimGeometry/tree/master/Xbim.Geometry.Engine.Interop.Tests)

**Comment by andyward** [comment]
For simple test setups, I'd think that having these unit tests entirely encapsulated in code would be good thing. (rather than being dependent on a more complex IFC file maintained separately). But it seems we do both, depending on the complexity of the test case,

Building model in code: https://github.com/xBimTeam/XbimGeometry/blob/24a3db9442b33578eebf9fbf2eb58074cc3afc56/Xbim.Geometry.Engine.Interop.Tests/IfcCSGTests.cs#L40

Building model from File: https://github.com/xBimTeam/XbimGeometry/blob/24a3db9442b33578eebf9fbf2eb58074cc3afc56/Xbim.Geometry.Engine.Interop.Tests/IfcAdvancedBrepTests.cs#L71

Does it cause an issue?

**Comment by Hafplo** [comment]
I was trying to reproduce the tests using real IFC files and I thought I need the [IfcModelBuilder](https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.Geometry.Engine.Interop.Tests/IfcModelBuilder.cs) to apply them.

Now I realize it is just to produce mock data for the tests.

The tests will be clearer to build the model *outside* the test or just use small IFC files, since they are closer to real data.

Anyway, I got an answer, closing the issue.
