### ISSUE TITLE
Objects missing when opening IFC file

### ISSUE THREAD

**Issue by IFChaos** [xBimTeam/XbimGeometry#4]
Hello, first of all i want to say that you are doing a great job.

Now the problem i find:
I have an IFC file that Xbim seems unable to load properly. When i open this IFC file using XbimXplorer many objects are missing. But these objects are visible using SOLIBRI.
If i could send this file to you, then maybe you will be able to detect where is the problem.

Thank you!!

**Comment by andyward** [comment]
If you can share the model somewhere, and provide some details on what you think is missing I'll take a look. Also provide the version of XbimExplorer you're using (or the branch).

If it's a core Geometry issue it'll probably need Steve.

**Comment by IFChaos** [comment]
SOLIBRI MODEL VIEWER is free, you can download it and compare yourself the model opened with SOLIBRI with the model opened by XbimXplorer.

I posted the file here http://we.tl/hAg5a37QYY

If there is any problem downloading the model just tell me.

**Comment by andyward** [comment]
So it looks like XbimXplorer needs the latest Geometry Engine. It's using 3.0.21 but this has an issue which @SteveLockley has since fixed (in the upgrade to latest OCC libraries). I was able to get the model to render fine by processing the IFC to XBIM using the latest Geometry code (in a standalone tool), and then load it in XbimXplorer & WebUI. 

When Steve publishes the latest Geometry Nuget package we'll flush this through the stack to Xplorer.

Here it is working (using latest Xbim.Geometry develop code) :

![image](https://cloud.githubusercontent.com/assets/923699/8304445/d1bef8ce-199d-11e5-9df4-e48681936755.png)

and broken (converted with 3.0.21 xbim.geometry)

![image](https://cloud.githubusercontent.com/assets/923699/8304514/7a9f4462-199e-11e5-87d8-9c2dc6293abf.png)

**Comment by IFChaos** [comment]
Perfect

I'm using Nuget to add Xbim functionality to a C# application. I have to update "Xbim geometry" Nuget to solve the problem? 

And now a newbie question: What i have to do in VB 2012 to update a Nuget?

**Comment by andyward** [comment]
The trouble is that the latest published Xbim Geometry hasn't been updated and still has the issue. I used a pre-release version I built myself. I'd advise waiting for the team to get an official package out there unless you're totally blocked...

I assume you mean VS2012, rather than VB2012? In terms of nuget you should probably take a look at [Nuget Docs] (http://docs.nuget.org/consume/overview) (see the section on [Updating a package] (http://docs.nuget.org/Consume/Package-Manager-Dialog#user-content-updating-a-package) ). Right now there is no update on the official nuget feed so you won't see anything from Xbim in the Updates section.

**Comment by IFChaos** [comment]
Ok i can wait, no problem.

**Comment by CBenghi** [comment]
Hello, 
I'm closing this issue because it's probably been fixed by recent updates, but the file to test is not available any more at the link provided.
Please test it with a recent master update and reopen if needed.
Best,
Claudio
