### ISSUE TITLE
Documentation doesnt have info on xBIM.ModelGeometry.Scene 

### ISSUE THREAD

**Issue by ani-rudh** [xBimTeam/XbimGeometry#43]
Hello @SteveLockley ,
 I have been unsuccesful in finding any documentation on xBIM.ModelGeometry [here](http://docs.xbim.net/XbimDocs/html/eb3d64e2-3ae5-476f-8790-caf1be5aabee.htm). 

Is it missing or am I looking at the wrong documentation version?!

This class seems very helpful for my task but I cannot find any documentation on that.

As a side note, when I tried to build the xbim.docs solution on VS 2015, it failed saying its incompatible with my version of VS.

Help a noob!

Thanks in advance,
Ani

**Comment by CBenghi** [comment]
Hello @ani-rudh,
I think to open the docs solution you need to install https://github.com/EWSoftware/SHFB 
We are always short of resources to work on documentation, so if you can break down your request into specific issues that you'd like to understand we could provide answers for you to put into proper documentation.
This is I think the front where the community can more easily make the difference, from our perspective it's difficult to understand what the documentation priorities are.

Would you mind creating a list of priorities for the parts that are harder to understand?

Thanks,
Claudio

PS. I'll close this issue, but only so that you can open a new one with a clearer set of requests.
