### ISSUE TITLE
IfcOpenShell invalid cast exception

### ISSUE THREAD

**Issue by dontbmh** [xBimTeam/XbimGeometry#45]
Hi, this is my test code.

`                var store = IfcStore.Open(file, null, null);
                var storeGem = store.GeometryStore;
                if (storeGem.IsEmpty)
                {
                    var context = new Xbim3DModelContext(store);
                    context.CreateContext();
                }
                foreach (IReferencedModel model in store.ReferencedModels)
                {
                    if (model.Model == null)
                        continue;
                    if (!model.Model.GeometryStore.IsEmpty)
                        continue;
                    var context = new Xbim3DModelContext(model.Model);
                    context.CreateContext();
                }`

However, on Xbim3DModelContext line 1160,
var shape = (IIfcGeometricRepresentationItem)Model.Instances[shapeId];
would throw an invalid cast exception, when the shape is type of ifcopenshell.

added:
also I got many error logs like
ERROR Xbim.Geometry.XbimGeometryCreator [(null)] - GeomEngine: #1494000=IfcCartesianPoint [Geometry Representation of Type IfcCartesianPoint is not implemented]

Any suggestions?

Cheers.

**Comment by dontbmh** [comment]
[S2.zip](https://github.com/xBimTeam/XbimGeometry/files/867998/S2.zip)
I've attached my test ifc file here.

**Comment by dontbmh** [comment]
Is there a need to add a restriction for IIfcGeometricRepresentationItem when generating ProductShapeIds?

**Comment by CBenghi** [comment]
Hello there,
I've made a couple of changes to geometry to handle the error more gracefully and load most of the model. There are still problems with the file and I've added a test case to geometry to keep track of the problem. 
I'll involve @SteveLockley here to make sure that we don't introduce regressions and come back to you.
Best,
Claudio

**Comment by CBenghi** [comment]
Hello,
I'm back with bad news I'm afraid.
The reason of the problem seems to sit with an invalid structure of the file.
I've extracted the minimal case to reproduce the error in this file:

https://github.com/xBimTeam/XbimGeometry/blob/22f8c436f927c38dc76dfb75ec1814c9f92b599e/Xbim.Geometry.Engine.Tests/SolidTestFiles/CatiaIfcOpenShellTest.ifc

But then looking at it it emerged that the problem is in the file.

IfcShapeRepresentations have specific where clauses in the ifc schema that constraint the types that it accepts and the one in question (Entity #1494003) fails two requirements:

WR22	 : 	No topological representation item shall be directly used for shape representations, with the exception of IfcVertexPoint, IfcEdgeCurve, IfcFaceSurface. And,
WR24	 : 	Checks the proper use of Items according to the RepresentationType.

This is actually a problem that you should notify the good folks of Catia; They should export an IFCSHELLBASEDSURFACEMODEL between the rapresentation and the IfcOpenShell.

The fix on the model is simple and it's as follows:
#1494003 needs to be changed and #1775737 to be added from scratch. 

#1494003=IFCSHAPEREPRESENTATION(#14,'BODY','SurfaceModel',(#1775737));
#1775737=IFCSHELLBASEDSURFACEMODEL((#1503330));

you can download the fixed file from https://github.com/xBimTeam/XbimGeometry/blob/b97b017cfb3c8e32b0a9bd191b2a0763cd72b348/Xbim.Geometry.Engine.Tests/SolidTestFiles/CatiaIfcOpenShellTest.ifc

I hope this helps.
Claudio

**Comment by dontbmh** [comment]
Thanks for your detail reply. 

According to buildingsmart's specs, I believe you are right. 
A topological representation directly used for shape seems violate the ifc definition.
I would make a temporarily fix on my fork in order to complete my export work and contact catia later.

Cheers.
Dirk
