### ISSUE TITLE
Is v6 geometry engine currently much slower than v5??

### ISSUE THREAD

**Issue by jomijomi** [xBimTeam/XbimGeometry#473]
Hi, earlier this week I tried out the v6 (netcore branch, compiled with VS2022) geometry engine together with Andy’s updated XbimWindowsUI (pull request 196: IFC 4x3 integration) and it appears to be much slower on most files compared to v5 (XbimWindowsUI-master, compiled with VS2022). I know this is work-in-progress, and my point is not really to question the current state/performance, but instead to rule out any mistakes done by me when compiling the libraries, etc. For instance, I clearly see v6 being much slower if I try with the standard IFC exports of Revit Basic Sample and the different disciplines from West Riverside Hospital (from the Open IFC Model Repository). Now, for the RVT Basic Sample I do get several “IfcFacetedBrep” which gets a “Long meshing time of shape geometry”, around 80 s. each, but the overall pattern when importing a number of different IFC files is that it is consistently (much) slower compared to v5. Is this to be expected at this point, or am I doing something wrong?

Best,
Mikael

**Comment by andyward** [comment]
I did some testing on this and you're right - it's taking 20-30 secs to process a single moderately complex representation item. We've not hit it ourselves internally as we don't directly use the Scene/Xbim3DModelContext code - we drive the GeoemetryEngine and Tessellator directly.

The issue is that in v6 mode, rather than use the XbimTessellator directly we convert to BREP using OCC and then use OCC's Tessellator - which seems to be orders of magnitude slower. The only reason for this is accurate QTO (vs quantities from a mesh). 

For now what I've done is change the default behaviour to be as per v5, and make Breps an explicit opt-in for V6, when Creating a Scene.

We do need to look at performance still as really the BREP step should not be adding quite the overhead it is. Suggest we pick that up in a separate ticket.
