### ISSUE TITLE
WexBim file size?

### ISSUE THREAD

**Issue by DrorSegev** [xBimTeam/XbimGeometry#49]
Hi.
I'm using a standard in-session IFC export from revit.
My IFC File size in about 30M.
The output wexbim file size is 160M
This is wired cause in most cases wexbim size is about 10% of IFC.
What should I check?

Dror

**Comment by DrorSegev** [comment]
More info: 
when running this code on the model:
 var items = model.Instances.OfType<IfcRepresentationItem>().GroupBy(i => i.GetType());
                foreach (var item in items)
                {
                    Console.WriteLine($"Type: {item.Key.Name}, Count: {item.Count()}");
                }
The following is the results:
Type: IfcAxis2Placement2D, Count: 1250
Type: IfcAxis2Placement3D, Count: 25577
Type: IfcCartesianPoint, Count: 139955
Type: IfcDirection, Count: 4194
Type: IfcCompositeCurve, Count: 17719
Type: IfcPolyline, Count: 41893
Type: IfcTrimmedCurve, Count: 23432
Type: IfcCircle, Count: 23432
Type: IfcPlane, Count: 56
Type: IfcCartesianTransformationOperator3D, Count: 1
Type: IfcCompositeCurveSegment, Count: 64986
Type: IfcBooleanClippingResult, Count: 56
Type: IfcHalfSpaceSolid, Count: 14
Type: IfcPolygonalBoundedHalfSpace, Count: 42
Type: IfcExtrudedAreaSolid, Count: 742
Type: IfcFacetedBrep, Count: 183
Type: IfcSweptDiskSolid, Count: 17576
Type: IfcFaceBasedSurfaceModel, Count: 4
Type: IfcStyledItem, Count: 456
Type: IfcConnectedFaceSet, Count: 4
Type: IfcClosedShell, Count: 183
Type: IfcPolyLoop, Count: 4599
Type: IfcFace, Count: 4576
Type: IfcFaceBound, Count: 23
Type: IfcFaceOuterBound, Count: 4576
Type: IfcMappedItem, Count: 149

What wrong with this model?

**Comment by DrorSegev** [comment]
I played with (before creating the context)
model.ModelFactors.Precision = 1;
model.ModelFactors.ProfileDefLevelOfDetail = 0;
model.ModelFactors.DeflectionTolerance = 2;
model.ModelFactors.DeflectionAngle = 3;

and it reduced the size, but I do not know why
Dror

**Comment by SteveLockley** [comment]
Your settings reduced the file size because you have change the tolerances for triangulation.
If you have a sphere and set things like the deflection tolerance or deflection tolerance to large numbers like 2 or 3 you will end up with maybe 2-10 triangles. On the other hand if you set these  to very small values you could have millions of triangles. The defaults in Xbim take into consideration real world units (mm, metres etc) and adjust these values to get something sensible (100s of triangles). So the answer to your question is you have a lot of curved geometries that are being triangulated to a very high meshing precision, the most likely problem is your real world units are not specified correctly
