### ISSUE TITLE
IfcSweptDiskSolid trim bug

### ISSUE THREAD

**Issue by urosjovanovic** [xBimTeam/XbimGeometry#50]
Hello all,

I've isolated the case where IfcSweptDiskSolid geometry is not generated correctly.
The problem seems to be caused by trim parameter values not being in radians.

Take a look at attached images. The first image shows correct geometry inside Solibri Model Viewer.
The second image shows the same IFC loaded in Xbim.
The third image shows workaround which causes Xbim to generate the correct geometry.

![rebar-solibri](https://cloud.githubusercontent.com/assets/5221157/24919923/913280c4-1ee5-11e7-8db5-f531d3e59087.PNG)
![rebar-xbim](https://cloud.githubusercontent.com/assets/5221157/24919924/913bd368-1ee5-11e7-8f88-2782183e0293.PNG)
![ifcsnippet](https://cloud.githubusercontent.com/assets/5221157/24919922/91312544-1ee5-11e7-8265-fe52010f626c.png)

[REBAR.zip](https://github.com/xBimTeam/XbimGeometry/files/914398/REBAR.zip)

**Comment by CBenghi** [comment]
Hello,
I'm looking into this, it's (as always) more complicated than it first seems.
I'll keep you posted.
Claudio

**Comment by CBenghi** [comment]
Hi @urosjovanovic ,
this problem is fixed in the latest version of the develop branch.
Commit hash:	e94d0e24515b3f1f21542e0cb6b9ee86aca4b296
I think that the code still has some issues but this file is read correctly now and the code is included in the latest develp branch of windowsUI as well.
Let me know if this works for you.
Claudio

![image](https://cloud.githubusercontent.com/assets/5476273/25148747/e1d6a12a-2473-11e7-806f-c2e633e66d71.png)

**Comment by urosjovanovic** [comment]
Hi @CBenghi ,
I've tried to load the problematic file again and everything looks OK now.
Is there any info on when to expect the updated NuGet packages on master?

Thank you for the fast reply and fix, it is much appreciated!

Best regards,
Uros
