### ISSUE TITLE
Are there performance metrics ?

### ISSUE THREAD

**Issue by PIUM-arc** [xBimTeam/XbimGeometry#511]
Hello, 
I would like to know if there are any performance metrics regarding the geometry, especially the relation between the size of an IFC file and the time needed to load it. 
Thanks

**Comment by andyward** [comment]
Not really, since it's not a direct correlation between file size and geometry performance. It's geometry calculations like boolean operation (and nested booleans) that often have a major impact on performance. i.e. cutting holes in solids. A very large model consisting of a complex pre-calculated meshes might appear large but would generally be quick to process.
Also bear in mind a lot of a file's content could be semantic data, and largely irrelevant to geometry processing.

If I were to benchmark, I'd probably suggest it should be time against # of IfcShapeRepresentations - but you'd likely want to account for the different representation types (like IfcBooleanResult) - as discussed above these have a large bearing on performance.

What were you hoping to understand from performance metrics?

**Comment by PIUM-arc** [comment]
Thanks for the details.
The most common question we receive is: 'I have an IFC file of this size; how long would it take to load?' That’s why I’m wondering if you might have some metrics regarding this.
From what I understand, we could analyze the IFC file to count the IfcShapeRepresentations and IfcBooleanResult instances.

**Comment by andyward** [comment]
Sorry - there's too many variables to given an answer other than "It depends"! 

It depends on what 'load' means, whether you're desktop or cloud based, what kind of model it is, what the use case is etc, tech resources/specs will have a bearing (32bit/64bit, CPU and RAM).. 
In a cloud environment you may only take the geometry hit once. In a desktop tool starting with STEP IFC you probably take the pain every time.

If it's slow there may be optimisations you can make in xbim (e.g. entity caching, different IModel implementations etc). 

But there's single answer. 1 GB model will take longer to load than a 1 MB model 99.9% of time. But you could probably construct a 1MB model that would take forever to open too.
