### ISSUE TITLE
Precision setting in geometry engine.

### ISSUE THREAD

**Issue by CBenghi** [xBimTeam/XbimGeometry#58]
Hello @SteveLockley,

The geometry engine considers model precision to perform solid operations, however the value that precision is using might differ from one primitive to another.

Some parts of the code use
``` cs
var precision = Math.Max(_model.ModelFactors.OneMilliMeter / 50, _model.ModelFactors.Precision);
```
which is then used in some functions in scene, whereas c++ functions frequently use the model precision directly
``` cs
double precision = repItem->Model->ModelFactors->Precision;
```
is this deliberate?

One idea is to add a getter for the precisino value somewhere (possibly in modelfactors) retuning the required precision, that should be used across the geometric engine. does this make sense? Or maybe we need more than one to use in different scopes? 

Either way I think we need to clean up that aspect of geometry.
Any comments?

Thanks,
Claudio

**Comment by SteveLockley** [comment]
Historically some BIM tools did not observe precision correctly and when perfroming Booleans this cause major problems. Over the years they have got better, for instance Revit started with 1e-9, then used 1e-5 for all units (mm and feet). Now it uses 1e-2 for mm, which is the accuracy of its geometry engine.
Generally for a vertext obey the precision in the ifc file representation context. And Edge must be smaller and a face smaller still. For booleans use real world based numbers i.e. typical 0.01 millimeters is accurate enough. I have tidied several of these for release 5, but am reluctant to go full on as it is more of an art than a science. All tools do different things in different combination which is why we have the multi-BIM vendor regression tests
