### ISSUE TITLE
variable vs interface

### ISSUE THREAD

**Issue by xlor** [xBimTeam/XbimGeometry#59]
Good evening.
Regards from Spain.
It's my first time here, and I hope to find your support.
Recently I started learning your development. We want to thank you for your generosity, sharing your development. My background is architect and  my C# knowledge is short, but...

In this script, the error is "ifc es variable pero se usa como tipo" (IfnName is variable but it's used as type)

                string ifcName= cbx_ComboBoxIFc.SelectedValue.ToString()
                //The name of the IfcType is known: e.g. IIfcReinforcingBar, IIfcBeam, or other.
                //In this case from a ComboBox previously filled with the different types of Elements
                var elements = myWindow.Model.Instances.OfType<ifcName> ();
                foreach (var elem in elements)
                {
                   whatever... ;
                }
My question is: how can I use a variable to point to different interfaces as IIfcReinforcingBar, IIfcBeam or others.
Regards

**Comment by CBenghi** [comment]
Hello @xlor,
Ok, this is s bit complicated to explain.
It has to do with the concept of generic types in c#, you can read more about the topic here:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/

You know that IfcWindow and IfcRefinforcingBar, for instance have different properties, and the compiler knows what they are.

So if you ask the system for ```var v = Model.Instances.OfType<IfcWindow>()``` the runtime knows that each of the returned items is of the IfcWall type, so you can access its methods and properties.

But IfcWall in this case is not a string, rather it is the known .net type IfcWindow with its own methods and properties and the compiler can let you use them without checking what type of element is returned from the query, so that ```v[0].OverallHeight``` makes sense to the system.

We also have a different function ``` var v = Model.Instances.OfType("IfcWindow", true);``` that, as you can see, accepts a string instead of a type, but because a string is not guaranteed to have a value that makes sens to the compiler (it could have any values) then the returned value ```v``` is a collection of ```IPersistEntity``` which have only the properties that all the items in the database have in common and ```OverallHeight``` is not one of them, because it does not make sense if the returned item is a IfcRefinforcingBar.

You can still access all the properties of the instance returned, but you'll have to cast them to their own types for this to be working.

I hope this makes sense.

**Comment by CBenghi** [comment]
I'll just add a couple of lines to explain further...

Your ``` whatever... ;``` part of the code will do something with the items returned from the ```OfType()``` request, so if you want it to be able to use the ```OverallHeight``` property you'll have to know in advance that you are getting windows back from the database and use the generic invocation.

But if you are only interested in the entityLabel of the item, or counting them, then the non generic version (the one with the string) will be the one you need.

Welcome to the wonderful world of .net

:-D

(a fellow architect)

**Comment by xlor** [comment]
Thank you Claudio for your accurate explanation.

Knowing the EntityLabel parameter of an item, later we can call the rest of the parameters through:

            var elem = Model.Instances.FirstOrDefault<IIfcReinforcingBar>(d => d.EntityLabel.ToString() == id);
           // e.g. elem.GlobalId  or elem.NominalDiameter and so on.

but as you have commented we need to know that it's, for instance, a IfcReinforcingBar element.

It's ok though, but as far as I have understood,  we are oblied to write more similar lines of code for the different Ifc types.

            var elem = Model.Instances.FirstOrDefault<IIfcReinforcingBar>(d => d.EntityLabel.ToString() == id);
            ...
            var elem = myWindow.Model.Instances.FirstOrDefault<IIfcBeam>(d => d.EntityLabel.ToString() == id);
            ...
            var elem = myWindow.Model.Instances.FirstOrDefault<IIfFooting>(d => d.EntityLabel.ToString() == id);

Regards from Bilbao, and it's a pleasure to find an architect in these stuffs.

Jorge

**Comment by CBenghi** [comment]
yes, that is an option.
Your code can be also made more versatile by avoiding multiple queries, consider for instance:

```cs
foreach (var instance in model.Instances)
{
	Debug.WriteLine("The label is {0}", instance.EntityLabel);
	if (instance is IIfcReinforcingBar)
	{
		var asRebar = (IIfcReinforcingBar) instance;
		Debug.WriteLine("This instance is a Rebar and its lenght is  {0}", asRebar.BarLength);
	}
	else if (instance is IIfcWindow)
	{
		var asRebar = (IIfcWindow)instance;
		Debug.WriteLine("This instance is a IIfcWindow and its OverallHeight is  {0}", asRebar.OverallHeight);
	}
}
```

or querying to the level of interest in the class hierarchy:

``` cs
foreach (var instance in model.Instances.OfType<IIfcRoot>())
{
	Debug.WriteLine("Root objects all have GUID, this one is {0}", instance.GlobalId);
}
```
Best luck with your coding.
