### ISSUE TITLE
log4net issue

### ISSUE THREAD

**Issue by iwacky** [xBimTeam/XbimGeometry#88]
Hi team,

When I call `IfcStore.Open(path)`, I obtain error message:

> Could not load file or assembly 'log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a'
> AVT : Comparison of assembly is incompatible : principal version

My App.config redirect pre v2.0.8.0 binding to v2.0.8.0:
`<configuration>
...
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="log4net" publicKeyToken="669e0ddf0bb1aa2a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.8.0" newVersion="2.0.8.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
`

But doe not works.
Some help will be welcome

Important note: I am developing a DLL addin for a third party software.

**Comment by iwacky** [comment]
I updated log4net to 2.0.8 version. This is the source of my error.
I finally downgrade to 2.0.5 (1.2.15.0) and I no longer have this error message.

**Comment by CBenghi** [comment]
Hello @iwacky,
good to know that you have found a Solution.
I'd ask you to get in touch with me, if possible, as we are trying to log experiences from users and we also need some information from adoption in order to make an impact case study for our university.

If possible, please get in touch in pvt claudio.benghi@northumbria.ac.uk 
I'd only like to ask a couple of questions.

Thanks,
Claudio

**Comment by iwacky** [comment]
Hello Claudio,

No problem, I just send you a mail to exchange in private.

Regards
